### ISSUE TITLE
where to find the 43,191 newly recovered metagenome-assembled genomes (MAGs)?

### ISSUE THREAD

**Issue by liamxg** [BGI-Qingdao/GOMC#1]
Dear @DantongWang,

Could. I know. where to find the 43,191 newly recovered metagenome-assembled genomes (MAGs)?

Thanks.

Best,
Liam

**Comment by DantongWang** [comment]
Hi Liam,

please find the data here: https://db.cngb.org/maya/datasets/MDB0000002
You can download whichever you need by simply clicking "Download" on the left hand side.

Best,
Dantong
