### ISSUE TITLE
where to find the "data/figure1a.global_distribution.txt"file?

### ISSUE THREAD

**Issue by liamxg** [BGI-Qingdao/GOMC#2]
Dear @DantongWang,

Could. I know where to find the "data/figure1a.global_distribution.txt" file, thanks.

Best,
Liam

**Comment by DantongWang** [comment]
Hi Liam,

sorry for the late reply. We just updated the repository. 
Now you can find the file here: Rscript_v20240714/main_figure_data.zip

Best,
Dantong

**Comment by liamxg** [comment]
Dear @DantongWang,

Cool!

That's amazing!

Could I add your WetChat if you have one, thanks.

Best,
Liam

**Comment by DantongWang** [comment]
check if you can add me with: w295394293
